[package]
distribution = "2201.11.0"
org = "ballerinax"
name = "aws.secretmanager"
version = "0.3.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["AWS", "Secret Manager", "Cloud/Subscriptions"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.secretmanager"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "aws.secretmanager-native"
version = "0.3.0-SNAPSHOT"
path = "../native/build/libs/aws.secretmanager-native-0.3.0-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "time-native"
version = "2.6.0"
path = "./lib/time-native-2.6.0.jar"
