[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "aws.secretmanager"
version = "0.1.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["AWS", "Secret Manager", "Cloud/Subscriptions"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.secretmanager"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.lib"
artifactId = "aws.secretmanager-native"
version = "0.1.0"
path = "../native/build/libs/aws.secretmanager-native-0.1.0.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "time-native"
version = "2.5.0"
path = "./lib/time-native-2.5.0.jar"
